name: Improve Docs
description: Report a bug or propose an improvement.
title: "<short description>"
labels: ["unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our docs. Please complete the following so we can have the details necessary to assist you.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting a new issue.
      options:
        - label: I checked the [latest version of the documentation](https://docs.fetch.ai/).
          required: true
        - label: I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure my problem has not already been reported.
          required: true
        - label: I have read the [code of conduct](../../CODE_OF_CONDUCT.md) before creating this issue.
          required: true
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project is this issue about?
      options:
        - Ledger
        - CosmPy
        - Wallet
        - AEA Framework
        - Collective Learning
        - Something else
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What is this issue about?
      options:
        - Bug
        - Improvement
        - General suggestion
        - Something else
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: More details
      description: Give a detailed description of the bug/improvement/suggestion.
    validations:
      required: true
  - type: textarea
    id: assets
    attributes:
      label: Assets
      description: Files or links important for additional context on the issue.
    validations:
      required: false
